# Generated by Django 4.2.7 on 2023-11-29 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacy',
            unique_together={('chain', 'address')},
        ),
        migrations.CreateModel(
            name='ProductOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_of_the_day', to='bot.medication', verbose_name='Medication')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_of_the_day', to='bot.pharmacy', verbose_name='Pharmacy')),
            ],
            options={
                'verbose_name': 'Product of the day',
                'verbose_name_plural': 'Products of the day',
                'unique_together': {('pharmacy', 'medication')},
            },
        ),
    ]
