# Generated by Django 4.2.7 on 2023-12-05 11:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_form_unit_alter_pharmacy_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacystock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price'),
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('name', 'dosage', 'quantity')},
        ),
    ]
