# Generated by Django 4.2.7 on 2023-12-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_pharmacystock_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacystock',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='bot.pharmacy', verbose_name='Pharmacy'),
        ),
    ]
