# Generated by Django 4.2.7 on 2023-12-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_medication_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.FloatField(blank=True, null=True, verbose_name='Dosage'),
        ),
    ]
